ktor {
    deployment {
        port = 5432
        port = ${?PORT}
    }
    application {
        modules = [ app.coaf.org.ApplicationKt.module ]
    }
}

storage {
    driverClassName = "org.postgresql.Driver"
    jdbcURL = "jdbc:postgresql://localhost:5432/coaf_db"
    user = "nellyminasyan"
    password = "nellyminasyan"
}